set(CPACK_PACKAGE_NAME "Host Scanner")
set(CPACK_PACKAGE_VENDOR "RoliSoft")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
set(CPACK_PACKAGE_DESCRIPTION "Discover hosts on a network and gather information about them for later analysis.")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Host discovery and port scanning.")
set(CPACK_PACKAGE_FILE_NAME "HostScanner-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_PACKAGE_CONTACT "RoliSoft <root@rolisoft.net>")

set(CPACK_INSTALLED_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/build" "/bin")
set(CPACK_GENERATOR "DEB" "RPM")
set(CPACK_RESOURCE_FILE_LICENSE "LICENSE.md")
set(CPACK_RESOURCE_FILE_README "README.md")
set(CPACK_STRIP_FILES 1)

set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_RPM_PACKAGE_ARCHITECTURE "${CMAKE_SYSTEM_PROCESSOR}")

set(CPACK_DEBIAN_PACKAGE_SECTION "network")
set(CPACK_RPM_PACKAGE_GROUP "Applications/Internet")

set(CPACK_DEBIAN_PACKAGE_DEPENDS "libcurl3")
set(CPACK_RPM_PACKAGE_REQUIRES "libcurl")

set(CPACK_SOURCE_GENERATOR "DEB RPM")